language: node_js

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
    - export CXX="g++-4.8"

services:
    - cassandra
    - elasticsearch

node_js:
    - '4.2'
    - '5.0'

script:
    - npm test
